version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:pass@db/main
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: timescale/timescaledb:2.13.0-pg15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-init:
    build: ./airflow
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Mingyu --lastname Cha --role Admin --email admin@example.com --password admin
      "
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:pass@db/main
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - db
      - redis

  airflow:
    build: ./airflow
    command: webserver
    ports:
      - "9000:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:pass@db/main
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - airflow-init

  airflow-scheduler:
    build: ./airflow
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - airflow

  collector:
    build: ./collector
    volumes:
      - ./collector:/app  # collector 코드도 핫리로드 가능하게

volumes:
  pgdata: