version: '3.8'
services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db/main
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: timescale/timescaledb:2.13.0-pg15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    build: ./airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - db
      - redis

  airflow-scheduler:
    build: ./airflow
    command: airflow scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - airflow

volumes:
  pgdata:
